name: Compile LaTeX

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: doc
          ref: doc

      - uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Install texlive Apt dependencies
        run: sudo apt-get install texlive-base texlive-latex-extra texlive-science

      - name: Compile LaTeX
        run: |
          pdflatex main/doc/pow_xor_confuse.tex

      - name: Upload PDF
        run: |
          # Note: the following account information will not work on GHES
          cp pow_xor_confuse.pdf doc
          cd doc
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pow_xor_confuse.pdf
          git commit -m "upload generated pdf"
          git push origin doc
